[[introduction]]
= Вступление

Руководство по упаковке RPM пакетов:

Как подготовить исходный код для упаковки в RPM.:: Для тех, кто не имеет опыта разработки программного обеспечения.
xref:preparing-software-for-packaging[].

Как упаковать исходный код в RPM.:: Это для разработчиков программного обеспечения, которым необходимо упаковать программное обеспечение в RPMs. xref:packaging-software[].

Расширенные сценарии упаковки.:: Это справочный материал для упаковщиков RPM, работающих с расширенными сценариями упаковки RPM.                
 xref:advanced-topics[].

ifdef::community[]
[[pdf-version]]
== PDF Версия

Вы также можете скачать
https://rpm-packaging-guide.github.io/rpm-packaging-guide.pdf[PDF версию
данного документа].
endif::community[]

[[document-conventions]]
== Файловая структура

В данном документе используется следующая структура:

* Выходные данные команд и содержимое текстовых файлов, включая исходный код, размещаются в блоках:

+

[source,bash]
----
$ tree ~/rpmbuild/
/home/user/rpmbuild/
|-- BUILD
|-- RPMS    

[command output trimmed]
----

+

[source,txt]
----
Name:           bello
Version:
Release:        1%{?dist}
Summary:

[file contents trimmed]
----



+
[source,python]
----
#!/usr/bin/env python

print("Hello World")
----

* Темы, представляющие интерес, или словарные термины упоминаются либо как ссылки на соответствующую документацию или веб-сайт, выделенные **жирным** шрифтом, либо __курсивом__. Первые упоминания некоторых терминов ссылаются на соответствующую документацию.
ifdef::community[]
The first occurrences of some terms link to their respective documentation.
endif::community[]

* Названия утилит, команд и других элементов, обычно встречающихся в коде, написаны ``моноширинным`` шрифтом.

ifdef::community[]
include::contributing-to-this-guide.adoc[leveloffset=+1]
endif::community[]
