[[introduction]]
= Вступление

Руководство по упаковке RPM пакетов:

Как подготовить исходный код для упаковки в RPM.:: Для тех, кто не имеет опыта разработки программного обеспечения.
xref:preparing-software-for-packaging[].

Как упаковать исходный код в RPM.:: 
Это для разработчиков программного обеспечения, которым необходимо упаковать программное обеспечение в RPMs. xref:packaging-software[].

Расширенные сценарии упаковки.::
 Это справочный материал для упаковщиков RPM, работающих с расширенными сценариями упаковки RPM.                
 xref:advanced-topics[].

ifdef::community[]
[[pdf-version]]
== PDF Версия

Вы также можете скачать
https://rpm-packaging-guide-ru.github.io/rpm-packaging-guide-ru.pdf[PDF версию
данного документа].
endif::community[]

[[document-conventions]]
== Файловая структура

Перед тем, как приступить к сборке, нужно создать структуру каталогов, необходимую RPM, находящуюся в Вашем «домашнем» каталоге:

* Выходные данные команд и содержимое текстовых файлов, включая исходный код, размещаются в блоках:

+

[source,bash]
----
$ tree ~/rpmbuild/
/home/user/rpmbuild/
|-- BUILD
|-- BUILDROOT
|-- RPMS
|   |-- i586
|   |-- x86_64
|   `-- noarch
|-- SOURCES
|-- SPECS
`-- SRPMS

[command output trimmed]
----

+

[source,txt]
----
Name:           bello
Version:
Release:        1%{?dist}
Summary:

[file contents trimmed]
----



+
[source,python]
----
#!/usr/bin/env python

print("Hello World")
----

* Темы, представляющие интерес, или словарные термины упоминаются либо как ссылки на соответствующую документацию или веб-сайт выделены **жирным** шрифтом, либо __курсивом__. Первые упоминания некоторых терминов ссылаются на соответствующую документацию.

* Названия утилит, команд и других элементов, обычно встречающихся в коде, написаны ``моноширинным`` шрифтом.

ifdef::community[]
include::contributing-to-this-guide.adoc[leveloffset=+1]
endif::community[]
